Delete the bundle cache upon cache:clear
contao/manager-bundle pull request #16
Opened 2017-02-07 08:48 UTC by qzminski

… and before app is initialized after Composer install. Otherwise the container is not bootable if we install an extra bundle (say ```contao/calendar-bundle```) and then remove it from ```composer.json```. Then upon ```composer update``` command the bundle is being removed but its reference still sits in the ```$cacheDir/bundles.map``` and thus causes an error.

With regards to https://github.com/contao/managed-edition/issues/1

2017-02-07 15:53 UTC, aschempp requested changes
Looks very good to me, except for a few minor changes 👍

2017-02-07 15:53 UTC, aschempp commented on src/Composer/ScriptHandler.php
> +        static::purgeCacheFolder();
please add this after adding the app folder.

2017-02-07 15:53 UTC, aschempp commented on src/Cache/BundleCacheClearer.php
> +        $this->filesystem = $filesystem;
In all implementations I've seen, filesystem is usually an optional dependency (`= null` in the constructor). If it's not passed, create one on the fly.

2017-02-07 15:53 UTC, aschempp commented on tests/Cache/BundleCacheClearerTest.php
> +        $clearer = new BundleCacheClearer(new Filesystem());
You won't need to pass `Filesystem` if the constructor argument is optional.

2017-02-07 15:57 UTC, qzminski commented on src/Cache/BundleCacheClearer.php
> +        $this->filesystem = $filesystem;
I am not sure, @Toflar recommended the below as the similar solution so I just based it on that. Should we change it in the core as well then?

https://github.com/contao/core-bundle/blob/master/src/Cache/ContaoCacheClearer.php#L33

2017-02-07 15:57 UTC, qzminski commented on src/Composer/ScriptHandler.php
> +        static::purgeCacheFolder();
What's the reason? I'm curious.

2017-02-07 16:00 UTC, aschempp commented on src/Cache/BundleCacheClearer.php
> +        $this->filesystem = $filesystem;
Symfony does not even ask for the injection here: https://github.com/symfony/symfony/blob/5129c4cf7e294b1a5ea30d6fec6e89b75396dcd2/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/TemplatePathsCacheWarmer.php#L38

2017-02-07 16:00 UTC, aschempp commented on src/Composer/ScriptHandler.php
> +        static::purgeCacheFolder();
dunno, first initialize the app before "maintaining" it?

2017-02-07 20:29 UTC, qzminski commented on src/Composer/ScriptHandler.php
> +        static::purgeCacheFolder();
You don't initialize the app, just add the folder for it. Imo the order does not matter at all. Also the cache folder and app folder are not connected in any way.

2017-02-07 20:29 UTC, qzminski commented on src/Cache/BundleCacheClearer.php
> +        $this->filesystem = $filesystem;
Will change. Shall I also PR the core-bundle for that?

2017-02-13 12:19 UTC, aschempp commented
Merged in 30d6cbf76d927b4c33a1454fcb969889bc1d0c44

2017-02-13 12:19 UTC, closed without merging