kernel.projectDir must be set when initializing the kernel
contao/manager-bundle pull request #29
Opened 2017-05-08 13:22 UTC by aschempp

fixes #28

2017-05-08 13:27 UTC, ausi commented
Couldn’t we just use `dirname(dirname(dirname(dirname(dirname(__DIR__)))))` in `getProjectDir()` and not inject the path? Symfony itself also doesn’t inject the project dir but searches for the nearest composer.json file.

2017-05-08 13:28 UTC, aschempp commented
What if classes are combined for caching etc?

2017-05-08 13:30 UTC, ausi commented
I think since PHP 7 there is no need for caching PHP files by combining them. But even then, the caching script should handle the `__DIR__` constants correctly.

2017-05-08 14:05 UTC, ausi commented on src/HttpKernel/ContaoKernel.php
>      {
Should we add a `@trigger_error(, E_USER_DEPRECATED)` here?

2017-05-08 14:09 UTC, aschempp commented on src/HttpKernel/ContaoKernel.php
>      {
Valid point, added in b1702b93a48bd3f30fb9f6ff728fa2ee70b80da2

2017-05-10 06:59 UTC, leofeyer approved these changes

2017-05-10 21:03 UTC, ausi requested changes
If we want to go with the constructor argument, I think the following places have to be updated too:

- [src/Resources/system/initialize.php:22](https://github.com/contao/manager-bundle/blob/4d2babb216341cf46c8146fc50730028af6e8275/src/Resources/system/initialize.php#L22)
- [bin/contao-console:43](https://github.com/contao/manager-bundle/blob/4d2babb216341cf46c8146fc50730028af6e8275/bin/contao-console#L43)
- [tests/HttpKernel/ContaoKernelTest.php:53](https://github.com/contao/manager-bundle/blob/4d2babb216341cf46c8146fc50730028af6e8275/tests/HttpKernel/ContaoKernelTest.php#L53)

But I would still prefer the `dirname()` solution.

Also, isn’t changing the constructor arguments a BC break? E.g. what is if I use a custom *app_dev.php* in my project that uses the `ContaoKernel`, wouldn’t that break with an update?

2017-05-12 14:30 UTC, aschempp commented
I have fixed the remaining uses of `ContaoKernel::setProjectDir`. Regarding BC break, afaik the constructor is not a BC promise.

2017-05-12 14:33 UTC, Toflar commented
> Regarding BC break, afaik the constructor is not a BC promise.

Of course it is. You can only add arguments that are optional.

2017-05-17 08:37 UTC, leofeyer commented
I have updated the PR so it is backwards compatible. Please review again.

2017-05-17 09:35 UTC, leofeyer commented
We should also wait for https://github.com/symfony/symfony/pull/22727 before merging this PR.

2017-05-18 09:58 UTC, ausi commented on src/HttpKernel/ContaoKernel.php
> +            $this->projectDir = dirname(dirname(dirname(dirname(dirname(__DIR__)))));
With this line, the ContaoKernel now finds the path to the project dir itself. Why do we need the constructor argument then?

2017-05-18 11:05 UTC, leofeyer commented on src/HttpKernel/ContaoKernel.php
> +            $this->projectDir = dirname(dirname(dirname(dirname(dirname(__DIR__)))));
For the unit tests I guess.

2017-05-18 13:39 UTC, ausi commented on src/HttpKernel/ContaoKernel.php
> +            $this->projectDir = dirname(dirname(dirname(dirname(dirname(__DIR__)))));
In the unit tests we could compare the project dir path against the path of the ContaoKernel.php file.

2017-05-18 17:48 UTC, ausi approved these changes
One parameter doccomment is wrong IMO, the rest looks good to me 👍

2017-05-18 17:48 UTC, ausi commented on src/HttpKernel/ContaoKernel.php
> +     * @param string|null $projectDir
I think `null` should not be allowed here.

2017-05-19 07:15 UTC, merged

2017-05-23 19:40 UTC, leofeyer commented
Unfortunately, adding `$projectDir` as first argument leads to an exception upon install:

```
composer run-script post-update-cmd
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 Added/updated the web/app.php file.

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

21:37:54 ERROR     [console] Error thrown while running command "--ansi cache:clear --env=prod". Message: "Too few arguments to function Contao\ManagerBundle\HttpKernel\ContaoKernel::__construct(), 2 passed in /Users/leofeyer/Sites/contao/managed-edition/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 262 and exactly 3 expected" ["error" => ArgumentCountError {trace: { …} …},"command" => "--ansi cache:clear --env=prod","message" => "Too few arguments to function Contao\ManagerBundle\HttpKernel\ContaoKernel::__construct(), 2 passed in /Users/leofeyer/Sites/contao/managed-edition/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php on line 262 and exactly 3 expected"] []
21:37:54 ERROR     [console] Command "--ansi cache:clear --env=prod" exited with code "1" ["command" => "--ansi cache:clear --env=prod","code" => 1] []

  [Symfony\Component\Debug\Exception\FatalThrowableError]                      
  Type error: Too few arguments to function Contao\ManagerBundle\HttpKernel\C  
  ontaoKernel::__construct(), 2 passed in /Users/leofeyer/Sites/contao/manage  
  d-edition/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command  
  /CacheClearCommand.php on line 262 and exactly 3 expected                    
```

This is because the Symfony [CacheClearCommand](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L200) creates a temporary kernel, which of course does not know about our custom parameter.

So I guess there is no other way then making the third argument optional?