Implemented FirewallPluginInterface
contao/manager-bundle pull request #31
Opened 2017-05-08 16:21 UTC by aschempp

see #24

This solves the issue that security firewall configuration cannot be extended (`cannotBeOverwritten` is set on the `TreeBuilder`). I wonder if it would make sense to implement this as a general solution as we don't know if there are other such nodes?

2017-05-09 06:49 UTC, Toflar requested changes
Tests fail. Other than that looks good, thank you!

> I wonder if it would make sense to implement this as a general solution as we don't know if there are other such nodes?

To be honest, I can't think of one at the moment and we should not overcomplicate things right now as we're still in the early stages. I think the firewall is the 99% case and if there will be another one we might still build a general solution. Even if we build the general solution I still think it is a good thing to keep the `FirewallPluginInterface` because it is more specific in naming and pretty obvious why it's there. It might still map to a new, more general solution, in the future so we don't block anything here imho :)

2017-05-09 06:57 UTC, leofeyer commented on src/ContaoManager/Plugin.php
> +            Yaml::parse(file_get_contents(__DIR__.'/../Resources/contao-manager/security_firewalls.yml'))
Why are you not passing the loader as argument so we can do

```php
$loader->load('@ContaoManagerBundle/Resources/contao-manager/security_firewalls.yml');
```

?

2017-05-09 06:57 UTC, Toflar commented on src/ContaoManager/Plugin.php
> +            Yaml::parse(file_get_contents(__DIR__.'/../Resources/contao-manager/security_firewalls.yml'))
It has to be an array so you can order it. That's the whole point about this plugin :)

2017-05-09 07:02 UTC, leofeyer approved these changes

2017-05-11 13:06 UTC, aschempp commented
I have rewritten the implementation to use a more generic approach. The new `ExtensionPluginInterface` allows to process all extension configurations before they are used (basically, before they are processed by the extension).

This has several advantages:
 1. It's not specific to firewalls
 2. In regular cases, the interface is not needed at all
 3. It allows a plugin to modify **all** extension configuration from all bundles (even prepend), plugins and the application configuration itself.

The tests are currently failing because of #29

2017-05-11 13:21 UTC, leofeyer commented on src/HttpKernel/ContaoKernel.php
> +        if (class_exists('ProxyManager\Configuration') && class_exists('Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator')) {
You could use `Configuration::class` and `RuntimeInstantiator::class` here.

2017-05-11 16:12 UTC, aschempp commented on src/HttpKernel/ContaoKernel.php
> +        if (class_exists('ProxyManager\Configuration') && class_exists('Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator')) {
That code is a direct copy from Symfony so I'd rather not change it…?

2017-05-11 16:14 UTC, Toflar approved these changes

2017-05-12 06:36 UTC, leofeyer commented on src/HttpKernel/ContaoKernel.php
> +        if (class_exists('ProxyManager\Configuration') && class_exists('Symfony\Bridge\ProxyManager\LazyProxy\Instantiator\RuntimeInstantiator')) {
Agreed. :)

2017-05-22 09:55 UTC, merged